src/main/java/thunder/hack/Thunderhack.java, src/main/java/thunder/hack/cmd/Command.java, src/main/java/thunder/hack/core/Core.java, src/main/java/thunder/hack/core/ModuleManager.java, src/main/java/thunder/hack/injection/accesors/IPlayerMoveC2SPacket.java, src/main/java/thunder/hack/modules/misc/LagNotifier.java, src/main/java/thunder/hack/modules/player/AntiHunger.java
Перенес просто потому что иногда хочется отключить надпись про рубербанд. А антиханегр крашил сразу как его включаешь.
=> Перкинул lag notify в LagNotifitier (в миск). Пофиксил краш Антихангера

src/main/java/thunder/hack/modules/combat/Aura.java
Made shieldbreaker double click for a bit more knockback
fixed badpacket flag on grim when you block with a shield + attack
=> Slight aura fixes

src/main/java/thunder/hack/modules/render/ViewModel.java
Теперь ручка будит красива крутица и не летать по всему экрану 0-0
Я в шоках полных с такой красати
=> Фикс рука крутилка

src/main/java/thunder/hack/core/AsyncManager.java
без создания новой коллекции этот менеджер бесполезен.
=> AsyncManager better thread safety

src/main/java/thunder/hack/modules/combat/AutoBuff.java
due to the suggesting in discord, https://discord.com/channels/1140266441082404924/1164453899390943273/1164453899390943273
=> autobuff onground

src/main/java/thunder/hack/cmd/impl/CalcCommand.java, src/main/java/thunder/hack/cmd/impl/FriendCommand.java, src/main/java/thunder/hack/core/impl/CommandManager.java
=> [+]Calc command

.github/workflows/gradle.yml, README.md
just merge i think it works on my fork of this
=> Update all actions to Node20

.github/workflows/gradle.yml
set prerelease: true -> prerelease: false
=> Make the 'latest' tag easier to find

build.gradle
Upgraded Loom from version 1.4 -> 1.5
=> Upgrade Loom version

src/main/java/thunder/hack/modules/combat/Aura.java, src/main/java/thunder/hack/modules/misc/UnHook.java
[+]Added Trident in OnlyWeapon(Anonymous)
=> [+]Update Simple UnHook

src/main/java/thunder/hack/modules/combat/Aura.java
Renamed and changed the positions of some option in Aura to enhance its reliability.
=> Aura: Renames and position changes to enhance reliability

src/main/java/thunder/hack/modules/misc/Spammer.java
Я еблан Я еблан Я еблан Я еблан Я еблан Я еблан Я еблан Я еблан 
Забыл менять факт Забыл менять факт Забыл менять факт Забыл менять факт Забыл менять факт
=> Spammer improvements

src/main/java/thunder/hack/modules/movement/NoSlow.java
=> Add NoSlow for LFCraft (SUPEP NON BAPASABLE GRIM FORK) 

src/main/java/thunder/hack/modules/combat/Aura.java, src/main/java/thunder/hack/modules/movement/NoSlow.java
так называемое "как засрать пулл реквесты тх"
=> fix 300 iq moment in noslow and add lfcraft/vulcan/alice aim disabler

src/main/java/thunder/hack/cmd/impl/HorseSpeedCommand.java, src/main/java/thunder/hack/core/impl/CommandManager.java
=> [+]HorseSpeedCommand.java

src/main/java/thunder/hack/modules/combat/AutoBed.java, src/main/java/thunder/hack/modules/misc/ChatUtils.java
=> autobed and chatutils improvements 

src/main/java/thunder/hack/gui/hud/impl/PotionHud.java, src/main/java/thunder/hack/modules/render/NameTags.java
=> PotionHud fix and Nametags Self setting

src/main/java/thunder/hack/injection/MixinScoreboardPlayerScore.java, src/main/java/thunder/hack/injection/MixinTextVisitFactory.java, src/main/java/thunder/hack/modules/misc/NameProtect.java, src/main/java/thunder/hack/modules/render/NameTags.java
=> Added hideFriends option in NameProtect

src/main/java/thunder/hack/modules/client/ThunderHackGui.java, src/main/java/thunder/hack/modules/render/KillEffect.java
=> Added volume control in KillEffect

src/main/java/thunder/hack/modules/Module.java, src/main/java/thunder/hack/modules/client/ClickGui.java, src/main/java/thunder/hack/modules/render/TotemAnimation.java, src/main/java/thunder/hack/utility/render/animation/GearAnimation.java
=> Added speed setting/gear, modules that cannot be disabled are now always disabled

src/main/java/thunder/hack/modules/render/NameTags.java
=> NameProtect fix

jitpack.yml
у https://github.com/SlimeCraftSMP/SlimeLib эта хуйня сработала
=> if it dont work i will nuke jitpack

src/main/java/thunder/hack/gui/hud/impl/TargetHud.java
=> Absorption and non-player fix

src/main/java/thunder/hack/modules/combat/Aura.java
Надеюсь оно не сломается
А ещё я хотел поменять дефолтные значения но забыл но бляя делать ещё отдельный коммит ради этого ну хз ну хз
=> Elytra range override

src/main/java/thunder/hack/gui/hud/impl/TargetHud.java
озабоченный школьник не знал что в мини нурике надо поменять clamp а в целке запене его вообще не было
=> TargetHud fix

src/main/java/thunder/hack/gui/hud/impl/StaffBoard.java, src/main/java/thunder/hack/modules/misc/AntiAttack.java, src/main/java/thunder/hack/modules/player/AutoRespawn.java
AntiAttack Villagers
AutoRespawn AutoWaypoint
StaffBoard "зам" and "сотрудник"
=> AntiAttack Villagers, AutoRespawn AutoWaypoint, AutoRespawn AutoWaypoint StaffBoard "зам" and "сотрудник"

.github/workflows/gradle.yml
read title and that explains what it does
=> chore(workflows): fix auto-release repo name

src/main/java/thunder/hack/modules/render/StorageEsp.java
I was playing a game mode, where Chests give items when clicked, but the map contained many trapped chests as decoration. This PR adds a toggle and color selector to enable/disable trapped chests from the StorageESP :)
=> StorageESP: Add Trapped Chests

src/main/java/thunder/hack/features/modules/client/BaritoneSettings.java, src/main/java/thunder/hack/features/modules/combat/Aura.java
[+]BaritoneSettings DesktopNotifications
=> [+]Aura IgnoreNamed

src/main/java/thunder/hack/features/modules/render/NameTags.java, src/main/java/thunder/hack/injection/MixinClientPlayerInteractionManager.java
=> [+]Colored ping in NameTags

src/main/java/thunder/hack/features/hud/impl/LegacyHud.java
[/] Some improvements in LegacyHud
=> [+] Biome in LegacyHud

src/main/java/thunder/hack/features/modules/combat/TriggerBot.java
adds a small delay between every hit in triggerbot, which allows for better bypassing.
=> small delay

src/main/java/thunder/hack/features/modules/combat/TriggerBot.java
можно менять делей для триггера!! ура!!
=> customisable triggerbot delay
